# Generated by Django 5.0.6 on 2024-07-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_task_4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentmodel',
            old_name='name',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='parentmodel',
            name='owner_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
