# Generated by Django 5.0.6 on 2024-07-02 15:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_task_4', '0002_rename_name_parentmodel_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentmodel',
            name='number',
            field=models.CharField(default='08888345', max_length=100, validators=[django.core.validators.RegexValidator('^\\d+$', message='This field must be numeric.')]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='django_task_4.parentmodel'),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='alternative_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='owner_email',
            field=models.EmailField(default='default@example.com', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
