# Generated by Django 5.0.6 on 2024-07-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_task_4', '0003_parentmodel_number_alter_childmodel_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentmodel',
            name='alternative_name',
            field=models.CharField(max_length=50),
        ),
    ]
