# Generated by Django 5.0.6 on 2024-07-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_task_4', '0004_alter_parentmodel_alternative_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentmodel',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
